<?php
/* -------------------- INTRODUCTION -------------------- */

/* File: /web_server_root_directory/misc/whats_new_sections.php.
 * Purpose: Web page sections.
 * Used in: /web_server_root_directory/misc/whats_new.php.
 * Last reviewed/updated: 05 Oct 2018.
 * Published: 21 Sep 2016. */
return
   "<!-- This web page does not have an h2-h6 element in the section element. To avoid W3C Markup Validation Service (http://validator.w3.org/) warning, not error (Warning: Section lacks heading. Consider using h2-h6 elements to add identifying headings to all sections.), comment out the section element. Same for index.php, sitemap.php, glossary.php, and whats_new.php.
    <section>
-->
<!-- Resources are \"Added\". Instructional pages are \"Published\". Always keep when a page is \"Added/Published\". When a page is \"Major update\" remove prior \"Updated/Major update\". When a page is \"Updated\" remove prior \"Updated\". When a page is \"Updated\" keep prior \"Major update\". When a page is \"Updated/Major update\" remove prior \"Renamed\". When a page is \"Renamed\" without being \"Updated\" keep prior \"Updated/Major update\". When a page is \"Renamed\" and \"Updated\" remove prior \"Updated\" and keep prior \"Major update\". When a page is \"Renamed\" rename all refs to the page (including Updated/Major update/Added/Published) to the new name. When a page is \"Deleted\" remove prior \"Published\", remove prior \"Updated\, and mention page \"Deleted.\". When a page is \"Moved to discontinued\" keep prior \"Published\", remove prior \"Updated\", and do not mention page \"Moved to discontinued\". -->
     <ul class='link-list'>
      <li><a href='/javascript/web_browser_useragent_values.php'>Web Browser User-Agent String Values (learnwebcoding.com)</a> and <a href='/javascript/javascript_web_browser_detection_update.php'>JavaScript Web Browser Detection With Link To Download Update (learnwebcoding.com)</a>: Updated: 05 Oct 2018.</li>
      <li><a href='/html/template_explained.php'>Learn Web Coding Home Template Explained (learnwebcoding.com)</a>: Updated: 05 Oct 2018.</li>
      <li><a href='/css/css_testing_ground/visualize_user_agent_styles.html'>Visualize User Agent Styles (learnwebcoding.com)</a> and <a href='/css/css_testing_ground/visualize_bootstrap_337_styles.html'>Visualize Bootstrap v3.3.7 Styles (learnwebcoding.com)</a>: Updated: 26 Sep 2018.</li>
      <li>Visualize Bootstrap v3.3.5 Styles and Visualize Bootstrap v3.3.6 Styles: Deleted: 26 Sep 2018.</li>
      <li><a href='/css/index.php'>CSS (learnwebcoding.com)</a> Landing Page: Updated: 26 Sep 2018.</li>
      <li><a href='/css/css_testing_ground/index.php'>CSS Testing Ground (learnwebcoding.com)</a>: Updated: 26 Sep 2018.</li>
      <li><a href='/sitemap.xml'>Learn Web Coding Site Map (XML Version Per Sitemaps.org) (learnwebcoding.com)</a>: Updated: 26 Sep 2018.</li><!-- Submit to Google Webmaster Tools. -->
      <li><a href='/sitemap.php'>Learn Web Coding Site Map (HTML Version) (learnwebcoding.com)</a>: Updated: 26 Sep 2018.</li>
      <li><a href='/misc/original_content.php'>Original Content (learnwebcoding.com)</a>: Updated: 26 Sep 2018.</li>
      <li><a href='/html/index.php'>HTML (learnwebcoding.com)</a> Landing Page: Updated: 26 Sep 2018.</li>
      <li><a href='/javascript/index.php'>JavaScript (learnwebcoding.com)</a> Landing Page: Updated: 04 Sep 2018.</li>
      <li><a href='/javascript/javascript_reference/setTimeout_method.php'>JavaScript Feature Reference: <code>setTimeout()</code> Method Web Browser Support Test (learnwebcoding.com)</a>: Updated: 29 Jul 2018.</li>
      <li><a href='/javascript/javascript_reference/index.php'>JavaScript Feature Reference (learnwebcoding.com)</a>: Updated: 29 Jul 2018.</li>
      <li><a href='/javascript/angularjs_shopping_cart_spa.php'>AngularJS Shopping Cart Single Page Application (learnwebcoding.com)</a> Updated: 08 Jul 2018.</li>
      <li><a href='/php/simple_mysql_admin.php'>Simple MySQL Admin (learnwebcoding.com)</a>: Web page updated: 30 Jun 2018.</li>
      <li><a href='/html/template_download.php'>Learn Web Coding Home Template Download (learnwebcoding.com)</a>: Web page updated and application updated: 24 May 2018.</li>
      <li><a href='/index.php'>Learn Web Coding Home Page (learnwebcoding.com)</a>: Updated: 15 May 2018.</li>
      <li><a href='/javascript/javascript_reference/setTimeout_method.php'>JavaScript Feature Reference: <code>setTimeout()</code> Method Web Browser Support Test (learnwebcoding.com)</a>: Published: 10 May 2018.</li>
      <li><a href='/html/html_testing_ground/web_browser_retain_remove_content_f5.html'>Does The Web Browser Retain Or Remove Manually And Programmatically Entered/Displayed Web Page Content Upon F5 (Refresh/Reload)? (learnwebcoding.com)</a> and <a href='/javascript/javascript_reference/scrollIntoView_method.php'>JavaScript Feature Reference: <code>scrollIntoView()</code> Method Web Browser Support Test (learnwebcoding.com)</a>: Updated: 08 May 2018.</li>
      <li><a href='/javascript/javascript_reference/localStorage_object.php'>JavaScript Feature Reference: <code>localStorage</code> Object Web Browser Support Test (learnwebcoding.com)</a> and <a href='/javascript/javascript_reference/instanceof_operator.php'>JavaScript Feature Reference: <code>instanceof</code> Operator Web Browser Support Test (learnwebcoding.com)</a>: Updated: 07 May 2018.</li>
      <li><a href='/misc/versions_ie_ed_windows.php'>Versions Of Internet Explorer And Edge Included With And Supported By Windows 98/ME/2000/XP/Vista/7/8/8.1/10 (learnwebcoding.com)</a>: Updated: 04 May 2018.</li>
      <li><a href='/javascript/javascript_reference/defineProperty_method.php'>JavaScript Feature Reference: <code>defineProperty()</code> Method Web Browser Support Test (learnwebcoding.com)</a>: Updated: 28 Apr 2018.</li>
      <li><a href='/php/simple_mysql_admin.php'>Simple MySQL Admin (learnwebcoding.com)</a>: Application major update: 08 Apr 2018.</li>
      <li><a href='/css/css_techniques/style_checkboxes_radio_buttons.php'>CSS Technique: Style Checkboxes And Radio Buttons (learnwebcoding.com)</a>: Updated: 22 Mar 2018.</li>
      <li><a href='/javascript/javascript_techniques/breadcrumbs_navigation.php'>JavaScript Technique: Breadcrumbs Navigation (learnwebcoding.com)</a>: Updated: 10 Mar 2018.</li>
      <li><a href='/javascript/javascript_reference/isArray_method.php'>JavaScript Feature Reference: <code>isArray</code> Method Web Browser Support Test (learnwebcoding.com)</a>, <a href='/javascript/javascript_reference/rest_parameter.php'>JavaScript Feature Reference: Rest Parameter Web Browser Support Test (learnwebcoding.com)</a>, <a href='/javascript/javascript_reference/setPrototypeOf_method.php'>JavaScript Feature Reference: <code>setPrototypeOf()</code> Method Web Browser Support Test (learnwebcoding.com)</a>, <a href='/javascript/javascript_reference/spread_operator_object_literal.php'>JavaScript Feature Reference: Spread Operator In Object Literals Web Browser Support Test (learnwebcoding.com)</a>, and <a href='/javascript/javascript_reference/template_tag_syntax.php'>JavaScript Feature Reference: Template Tag Syntax Web Browser Support Test (learnwebcoding.com)</a>: Updated: 07 Mar 2018.</li>
      <li><a href='/javascript/javascript_reference/array_destructuring_syntax.php'>JavaScript Feature Reference: Array Destructuring Syntax Web Browser Support Test (learnwebcoding.com)</a>, <a href='/javascript/javascript_reference/json_object.php'>JavaScript Feature Reference: <code>JSON</code> Object Web Browser Support Test (learnwebcoding.com)</a>, <a href='/javascript/javascript_reference/object_destructuring_syntax.php'>JavaScript Feature Reference: Object Destructuring Syntax Web Browser Support Test (learnwebcoding.com)</a>, and <a href='/javascript/javascript_reference/parameter_default_value.php'>JavaScript Feature Reference: Parameter Default Value Web Browser Support Test (learnwebcoding.com)</a>: Updated: 06 Mar 2018.</li>
      <li><a href='http://jquery.com/'>jQuery Core (jquery.com)</a> updated from v3.2.1 to v3.3.1: 06 Mar 2018.</li>
      <li><a href='/javascript/javascript_reference/module.php'>JavaScript Feature Reference: Module Web Browser Support Test (learnwebcoding.com)</a>: Published: 05 Mar 2018.</li>
      <li><a href='/javascript/javascript_reference/promise_object.php'>JavaScript Feature Reference: <code>Promise</code> Object Web Browser Support Test (learnwebcoding.com)</a>: Updated: 24 Feb 2018.</li>
      <li><a href='/javascript/javascript_reference/promise_object.php'>JavaScript Feature Reference: <code>Promise</code> Object Web Browser Support Test (learnwebcoding.com)</a>: Published: 22 Feb 2018.</li>
      <li><a href='/javascript/javascript_shopping_cart_spa.php'>JavaScript Shopping Cart Single Page Application (learnwebcoding.com)</a> Updated: 15 Feb 2018.</li>
      <li><a href='/javascript/jquery_techniques/fix_content_top_viewport_upon_scrolling.php'>jQuery Technique: Fix Web Page Content To Top Of Viewport Upon Scrolling (learnwebcoding.com)</a>: Updated: 10 Feb 2018.</li>
      <li><a href='/javascript/javascript_reference/find_method.php'>JavaScript Feature Reference: <code>find</code> Method Web Browser Support Test (learnwebcoding.com)</a> and <a href='/javascript/javascript_reference/findIndex_method.php'>JavaScript Feature Reference: <code>findIndex()</code> Method Web Browser Support Test (learnwebcoding.com)</a>: Published: 09 Feb 2018.</li>
      <li><a href='/javascript/javascript_reference/class_syntax.php'>JavaScript Feature Reference: <code>class</code> Syntax Web Browser Support Test (learnwebcoding.com)</a> and <a href='/javascript/javascript_reference/propertyIsEnumerable_method.php'>JavaScript Feature Reference: <code>propertyIsEnumerable()</code> Method Web Browser Support Test (learnwebcoding.com)</a>: Published: 07 Feb 2018.</li>
      <li><a href='/javascript/javascript_reference/hasOwnProperty_method.php'>JavaScript Feature Reference: <code>hasOwnProperty()</code> Method Web Browser Support Test (learnwebcoding.com)</a>: Updated: 07 Feb 2018.</li>
      <li><a href='/javascript/javascript_reference/array_destructuring_syntax.php'>JavaScript Feature Reference: Array Destructuring Syntax Web Browser Support Test (learnwebcoding.com)</a> and <a href='/javascript/javascript_reference/object_destructuring_syntax.php'>JavaScript Feature Reference: Object Destructuring Syntax Web Browser Support Test (learnwebcoding.com)</a>: Published: 29 Jan 2018.</li>
      <li><a href='/javascript/javascript_reference/arrow_function_syntax.php'>JavaScript Feature Reference: Arrow Function Syntax Web Browser Support Test (learnwebcoding.com)</a>, <a href='/javascript/javascript_reference/bind_method.php'>JavaScript Feature Reference: <code>bind()</code> Method Web Browser Support Test (learnwebcoding.com)</a>, and <a href='/javascript/javascript_reference/create_method.php'>JavaScript Feature Reference: <code>create()</code> Method Web Browser Support Test (learnwebcoding.com)</a>: Updated: 26 Jan 2018.</li>
      <li><a href='/javascript/javascript_reference/arguments_object.php'>JavaScript Feature Reference: <code>arguments</code> Object Web Browser Support Test (learnwebcoding.com)</a>: Updated: 25 Jan 2018.</li>
      <li><a href='/javascript/javascript_reference/instanceof_operator.php'>JavaScript Feature Reference: <code>instanceof</code> Operator Web Browser Support Test (learnwebcoding.com)</a>: Published: 24 Jan 2018.</li>
      <li><a href='/javascript/javascript_reference/entries_method_array.php'>JavaScript Feature Reference: <code>entries()</code> Method On Arrays Web Browser Support Test (learnwebcoding.com)</a>, <a href='/javascript/javascript_reference/entries_method_map.php'>JavaScript Feature Reference: <code>entries()</code> Method On Maps Web Browser Support Test (learnwebcoding.com)</a>, <a href='/javascript/javascript_reference/entries_method_set.php'>JavaScript Feature Reference: <code>entries()</code> Method On Sets Web Browser Support Test (learnwebcoding.com)</a>, <a href='/javascript/javascript_reference/keys_method_array.php'>JavaScript Feature Reference: <code>keys()</code> Method On Arrays Web Browser Support Test (learnwebcoding.com)</a>, <a href='/javascript/javascript_reference/keys_method_map.php'>JavaScript Feature Reference: <code>keys()</code> Method On Maps Web Browser Support Test (learnwebcoding.com)</a>, <a href='/javascript/javascript_reference/keys_method_set.php'>JavaScript Feature Reference: <code>keys()</code> Method On Sets Web Browser Support Test (learnwebcoding.com)</a>, <a href='/javascript/javascript_reference/values_method_array.php'>JavaScript Feature Reference: <code>values()</code> Method On Arrays Web Browser Support Test (learnwebcoding.com)</a>, <a href='/javascript/javascript_reference/values_method_map.php'>JavaScript Feature Reference: <code>values()</code> Method On Maps Web Browser Support Test (learnwebcoding.com)</a>, and <a href='/javascript/javascript_reference/values_method_set.php'>JavaScript Feature Reference: <code>values()</code> Method On Sets Web Browser Support Test (learnwebcoding.com)</a>: Published: 12 Jan 2018.</li>
      <li><a href='/javascript/javascript_reference/map_object.php'>JavaScript Feature Reference: <code>Map</code> Object Web Browser Support Test (learnwebcoding.com)</a>: Updated: 11 Jan 2018.</li>
      <li><a href='/javascript/javascript_reference/isArray_method.php'>JavaScript Feature Reference: <code>isArray</code> Method Web Browser Support Test (learnwebcoding.com)</a>: Published: 05 Jan 2018.</li>
      <li><a href='/javascript/javascript_reference/typedArray_object.php'>JavaScript Feature Reference: <code>TypedArray</code> Object Web Browser Support Test (learnwebcoding.com)</a>: Updated: 04 Jan 2018.</li>
      <li><a href='/javascript/javascript_reference/set_object.php'>JavaScript Feature Reference: <code>Set</code> Object Web Browser Support Test (learnwebcoding.com)</a> and <a href='/javascript/javascript_reference/generator_object.php'>JavaScript Feature Reference: <code>Generator</code> Object Web Browser Support Test (learnwebcoding.com)</a>: Updated: 03 Jan 2018.</li>
      <li><a href='/javascript/javascript_reference/generator_function.php'>JavaScript Feature Reference: Generator Function Web Browser Support Test (learnwebcoding.com)</a>, <a href='/javascript/javascript_reference/generator_object.php'>JavaScript Feature Reference: <code>Generator</code> Object Web Browser Support Test (learnwebcoding.com)</a>, and <a href='/javascript/javascript_reference/typedArray_object.php'>JavaScript Feature Reference: <code>TypedArray</code> Object Web Browser Support Test (learnwebcoding.com)</a>: Published: 01 Jan 2018.</li>
      <li><a href='/javascript/javascript_reference/let_declaration.php'>JavaScript Feature Reference: <code>let</code> Declaration Web Browser Support Test (learnwebcoding.com)</a>: Updated: 01 Jan 2018.</li>
      <li><a href='/javascript/javascript_reference/new_target_metaproperty.php'>JavaScript Feature Reference: <code>new.target</code> Metaproperty Web Browser Support Test (learnwebcoding.com)</a>: Updated: 01 Jan 2018.</li>
<!-- Next oldest web page updates and web pages that frequently update and/or do not want to delete/retype:
      <li><a href='/html/valid_html5_template.html'>Valid HTML5 Template (learnwebcoding.com)</a>: Updated: 01 Dec 2017.</li>
      <li><a href='/css/css_techniques/style_textboxes_textareas.php'>CSS Technique: Style Textboxes And Textareas (learnwebcoding.com)</a>: Updated: 29 Nov 2017.</li>
      <li><a href='/misc/install_xampp_windows.php'>Install XAMPP For An Offline Development Environment With Apache And MySQL Running Locally On Windows (learnwebcoding.com)</a>: Updated: 28 Oct 2017.</li>
      <li><a href='/php/install_quickinstall_windows.php'>Install phpBB QuickInstall On Your Local Windows Web Server To Develop phpBB Board Styles (learnwebcoding.com)</a>: Updated: 16 Sep 2017.</li>
      <li><a href='/misc/glossary.php'>Glossary (learnwebcoding.com)</a>: Updated 08 Sep 2017.</li>
      <li><a href='/css/css_tutorial.php'>CSS Tutorial (learnwebcoding.com)</a>: Updated 13 Aug 2017.</li>
      <li><a href='/misc/index.php'>Misc (learnwebcoding.com)</a> Landing Page: Updated: 07 Jul 2017.</li>
      <li><a href='/php/index.php'>PHP (learnwebcoding.com)</a> Landing Page: Updated: 06 Jul 2017.</li>
      <li>Learn Web Coding now supports the Hypertext Transfer Protocol Secure (i.e., the https:// protocol), which means connections to <a href='https://www.learnwebcoding.com/'>LWC Home (www.learnwebcoding.com)</a>, <a href='https://blog.learnwebcoding.com/'>LWC Blog (blog.learnwebcoding.com)</a>, and <a href='https://forums.learnwebcoding.com/'>LWC Forums (forums.learnwebcoding.com)</a> are now encrypted: 13 Jun 2017.</li>
      <li><a href='/css/css_techniques/style_selectboxes.php'>CSS Technique: Style Selectboxes (learnwebcoding.com)</a>: Updated: 11 Jun 2017.</li>
      <li><a href='/javascript/jquery_techniques/index.php'>jQuery Techniques (learnwebcoding.com)</a>: Updated: 02 Jun 2017.</li>
      <li><a href='/html/web_page.php'>Learn Web Coding Home Template (learnwebcoding.com)</a>: Updated: 11 May 2017.</li>
      <li><a href='/php/index.php'>PHP (learnwebcoding.com)</a> Landing Page: Added: 10 May 2017.</li>
      <li><a href='/html/valid_html401_transitional_template.html'>Valid HTML 4.01 Transitional Template (learnwebcoding.com)</a>, <a href='/html/valid_html401_strict_template.html'>Valid HTML 4.01 Strict Template (learnwebcoding.com)</a>, <a href='/html/valid_xhtml10_transitional_template.html'>Valid XHTML 1.0 Transitional Template (learnwebcoding.com)</a>, <a href='/html/valid_xhtml10_strict_template.html'>Valid XHTML 1.0 Strict Template (learnwebcoding.com)</a>, and <a href='/html/valid_xhtml11_template.html'>Valid XHTML 1.1 Template (learnwebcoding.com)</a>: Updated: 08 Feb 2017.</li>
      <li><a href='http://fontawesome.io/'>Font Awesome (fontawesome.io)</a> implementation updated from v4.6.3 to v4.7.0: 04 Feb 2017.</li>
-->
     </ul>

<!--
    </section>
-->";
